-- Allow 'dream' as a valid source for agent goals generated by the dream system.
-- Migration 018 created the source CHECK constraint with only:
--   ('self', 'assigned', 'eval_loop', 'reflection')
-- but dreams.py creates goals with source='dream', causing a silent constraint
-- violation and "Failed to add dream goal" log spam.
ALTER TABLE agent_goals DROP CONSTRAINT IF EXISTS agent_goals_source_check;
ALTER TABLE agent_goals ADD CONSTRAINT agent_goals_source_check
    CHECK (source IN ('self', 'assigned', 'eval_loop', 'reflection', 'dream'));
