import Phaser from "phaser";
import { WorldManager } from "../world/WorldManager";
import { AgentSpriteManager } from "../agents/AgentSpriteManager";
import type { WebSocketClient } from "../network/WebSocketClient";

export class MainScene extends Phaser.Scene {
  private worldManager: WorldManager | null = null;
  private agentSpriteManager: AgentSpriteManager | null = null;
  private wsClient: WebSocketClient | null = null;

  constructor() {
    super({ key: "MainScene" });
  }

  setWebSocketClient(client: WebSocketClient): void {
    this.wsClient = client;
  }

  preload(): void {
    // Tileset images and sprite sheets loaded from cached assets.
    // Assets are generated by PixelLab on session startup and cached locally.
  }

  create(): void {
    this.cameras.main.setBackgroundColor("#1a1a2e");

    // World must be created first so sprites render on top of tiles
    this.worldManager = new WorldManager(this);
    this.worldManager.create();

    // Create agent sprites at their desk positions
    this.agentSpriteManager = new AgentSpriteManager(
      this,
      this.wsClient,
      this.worldManager,
    );
  }

  getWorldManager(): WorldManager | null {
    return this.worldManager;
  }

  getAgentSpriteManager(): AgentSpriteManager | null {
    return this.agentSpriteManager;
  }

  update(): void {
    // Game loop logic will be added as features are implemented.
  }
}
