#!/usr/bin/env bash
# Back up the private Paper Minecraft world (scheduled-friendly snapshot).
#
# This is the committed backup script referenced by
# docs/minecraft/backup-restore.md (issue #530, epic E2-5). A persistent
# world is irreplaceable; this takes a timestamped tar.gz of the world so a
# bad chunk, a botched build, or a dead disk does not lose it.
#
# It snapshots the world set generated by start-server.sh (issue #526) using
# the LEVEL_NAME from world.config (issue #527, epic E2-2):
#   - <LEVEL_NAME>/            the overworld save
#   - <LEVEL_NAME>_nether/     the Nether    (if present)
#   - <LEVEL_NAME>_the_end/    the End       (if present)
#   - server.properties        so a restore brings back the same world config
# into BACKUP_DIR/<prefix>-<UTC-timestamp>.tar.gz, then prunes the periodic
# series to the newest BACKUP_KEEP archives.
#
# CONSISTENCY: for a perfectly clean snapshot, stop the server first (or rely
# on Paper's autosave / an RCON `save-all flush`). A backup of a running
# server is usually fine but may catch a half-written chunk — see
# docs/minecraft/backup-restore.md.
#
# Usage:
#   scripts/minecraft/backup.sh            # create a backup, then prune
#   scripts/minecraft/backup.sh --list     # list archives, newest first
#   scripts/minecraft/backup.sh --dry-run  # show what would be archived; write nothing
#   scripts/minecraft/backup.sh --help
#
# Configuration (environment variables, all optional):
#   SERVER_DIR    Where the server/world lives      (default: ./minecraft-server)
#   WORLD_CONFIG  World-gen config (for LEVEL_NAME)  (default: <script dir>/world.config)
#   BACKUP_DIR    Where archives are written         (default: $SERVER_DIR/backups)
#   BACKUP_KEEP   How many periodic backups to keep  (default: 10)
#   BACKUP_PREFIX Archive name prefix                (default: world)
#
# Retention is per archive-PREFIX series: each run prunes only its own
# BACKUP_PREFIX series to the newest BACKUP_KEEP. So a routine scheduled
# backup (prefix "world") never deletes the safety snapshots restore.sh
# writes (prefix "pre-restore"/"pre-reset", via BACKUP_PREFIX) — those are
# only trimmed, independently, the next time restore.sh writes one of them.
set -euo pipefail

ok()   { echo "✓ $*"; }
info() { echo "  $*"; }
fail() { echo "✗ $*" >&2; }

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

SERVER_DIR="${SERVER_DIR:-./minecraft-server}"
WORLD_CONFIG="${WORLD_CONFIG:-$SCRIPT_DIR/world.config}"
BACKUP_DIR="${BACKUP_DIR:-$SERVER_DIR/backups}"
BACKUP_KEEP="${BACKUP_KEEP:-10}"
BACKUP_PREFIX="${BACKUP_PREFIX:-world}"

MODE="create"
case "${1:-}" in
    --list)    MODE="list" ;;
    --dry-run) MODE="dry-run" ;;
    --help|-h)
        # Print the contiguous comment header (skip the shebang, stop at the
        # first non-comment line) so help never leaks script code, and stays
        # correct if the header length changes.
        awk 'NR==1{next} /^#/{sub(/^# ?/,"");print;next}{exit}' "$0"
        exit 0
        ;;
    "") ;;
    *)
        echo "✗ Unknown argument: $1 (try --help)" >&2
        exit 2
        ;;
esac

# read_world_key KEY → value of the last "KEY=value" line in WORLD_CONFIG
# (or empty). Fixed allow-list reader: the file is parsed with sed, never
# sourced/executed, so a malformed or hostile world.config cannot run code.
# `tr -d '\r'` tolerates a Windows-edited (CRLF) config. Mirrors the reader
# in start-server.sh so backup/restore agree with it on LEVEL_NAME.
read_world_key() {
    [ -f "$WORLD_CONFIG" ] || return 0
    tr -d '\r' < "$WORLD_CONFIG" | sed -nE "s/^${1}=(.*)$/\1/p" | tail -n1
}

LEVEL_NAME="$(read_world_key LEVEL_NAME)"; LEVEL_NAME="${LEVEL_NAME:-world}"

# list_archives [glob] → archive paths in BACKUP_DIR, newest first.
# Ordering is by the embedded UTC timestamp (fixed-width, lexically
# chronological), so it is correct across prefixes and portable (no reliance
# on `find -printf` / BSD-vs-GNU `stat`).
list_archives() {
    local pattern="${1:-*}.tar.gz" f ts
    [ -d "$BACKUP_DIR" ] || return 0
    # $pattern is intentionally unquoted: it is a glob we want expanded.
    # shellcheck disable=SC2086
    for f in "$BACKUP_DIR"/$pattern; do
        [ -e "$f" ] || continue
        ts="$(printf '%s\n' "$f" \
            | sed -nE 's#.*-([0-9]{8}T[0-9]{6}Z)\.tar\.gz$#\1#p')"
        [ -n "$ts" ] || ts="00000000T000000Z"
        printf '%s\t%s\n' "$ts" "$f"
    done | sort -r | cut -f2-
}

if [ "$MODE" = "list" ]; then
    if [ -d "$BACKUP_DIR" ] && [ -n "$(list_archives)" ]; then
        ok "Backups in $BACKUP_DIR (newest first):"
        while IFS= read -r f; do
            [ -n "$f" ] || continue
            info "$(basename "$f")"
        done < <(list_archives)
    else
        info "No backups found in $BACKUP_DIR yet."
    fi
    exit 0
fi

# ── Collect the world set to archive ───────────────────
[ -n "$LEVEL_NAME" ] || { fail "LEVEL_NAME resolved empty — check $WORLD_CONFIG"; exit 1; }

if [ ! -d "$SERVER_DIR/$LEVEL_NAME" ]; then
    fail "No world folder at $SERVER_DIR/$LEVEL_NAME — nothing to back up."
    info "  Start the server once (scripts/minecraft/start-server.sh) to"
    info "  generate the world, or set SERVER_DIR/WORLD_CONFIG correctly."
    exit 1
fi

members=()
for d in "$LEVEL_NAME" "${LEVEL_NAME}_nether" "${LEVEL_NAME}_the_end"; do
    [ -d "$SERVER_DIR/$d" ] && members+=("$d")
done
[ -f "$SERVER_DIR/server.properties" ] && members+=("server.properties")

TS="$(date -u '+%Y%m%dT%H%M%SZ')"
ARCHIVE="$BACKUP_DIR/${BACKUP_PREFIX}-${TS}.tar.gz"

if [ "$MODE" = "dry-run" ]; then
    ok "Dry run — nothing written."
    info "Would archive (relative to $SERVER_DIR):"
    for m in "${members[@]}"; do info "  - $m"; done
    info "Would write: $ARCHIVE"
    info "Would keep newest $BACKUP_KEEP '${BACKUP_PREFIX}-' archives, prune older."
    exit 0
fi

mkdir -p "$BACKUP_DIR"

# Tar only the explicitly enumerated members (never the whole SERVER_DIR), so
# BACKUP_DIR is structurally excluded under the default layout. Defensively
# also --exclude it if a custom BACKUP_DIR is nested inside the world set.
TAR_CMD=(tar -C "$SERVER_DIR")
case "$BACKUP_DIR/" in
    "$SERVER_DIR"/*)
        rel="${BACKUP_DIR#"$SERVER_DIR"/}"
        TAR_CMD+=(--exclude="$rel" --exclude="./$rel")
        ;;
esac
TAR_CMD+=(-czf "$ARCHIVE" "${members[@]}")

if ! "${TAR_CMD[@]}"; then
    rm -f "$ARCHIVE"
    fail "Backup failed while writing $ARCHIVE"
    exit 1
fi
ok "Backed up world to $ARCHIVE"
info "Included: ${members[*]}"

# ── Prune the periodic series beyond BACKUP_KEEP ───────
n=0
while IFS= read -r f; do
    [ -n "$f" ] || continue
    n=$((n + 1))
    if [ "$n" -gt "$BACKUP_KEEP" ]; then
        rm -f "$f"
        info "pruned old backup: $(basename "$f")"
    fi
done < <(list_archives "${BACKUP_PREFIX}-*")
ok "Retention: keeping newest $BACKUP_KEEP '${BACKUP_PREFIX}-' archive(s)."
